name: Metrics
on:
  schedule:
    - cron: "20 4 * * *"
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Metrics (left)
        uses: lowlighter/metrics@latest
        if: ${{ success() || failure() }}
        with:
          user: la-guirlande
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics.left.svg
          plugin_languages: yes
          plugin_languages_details: bytes-size, percentage
          plugin_languages_ignored: dockerfile, makefile, shell
          plugin_languages_skipped: ar-cards, minecraft-among-us, skyblock-confinement
          plugin_languages_limit: 6
          plugin_habits: yes
          plugin_habits_charts: yes
          config_order: base.header, isocalendar, languages, habits
          config_timezone: Europe/Paris
      - name: Metrics (right)
        uses: lowlighter/metrics@latest
        if: ${{ success() || failure() }}
        with:
          user: la-guirlande
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics.right.svg
          base: ""
          plugin_followup: yes
          plugin_followup_indepth: yes
          plugin_stargazers: yes
          plugin_activity: yes
          plugin_activity_limit: 7
          config_order: followup, stargazers, activity
          config_timezone: Europe/Paris
